// KYA KAR RAHA HAI: Abhi local DB me jo RICH Kaggle data load hai (1756 properties + actors +
// leases/payments), use ek committable SQL file me dump karta hai -> db/seed-data.sql.
// KAISE: har table se rows padhke INSERT statements banata hai (data-only, koi schema/trigger
// nahi). Isse Docker/managed-host bina 11MB CSV ke bhi rich data load kar sakta hai:
//   mysql < schema.sql   (structure + triggers)
//   mysql property_mgmt < db/seed-data.sql   (rich data)
//
// Chalane ka tareeka:  node scripts/dump-seed.js   (pehle `npm run seed` chala ke DB bharo)
//
// NOTE: FK checks OFF rakhte hain taaki insert order pe na atke. Triggers schema me alag se
// hain (yahan dump nahi karte) — LEASE/PAYMENT insert pe wo fire honge par data consistent hai
// (leases Active, props Rented) isliye koi rejection nahi aata.

const fs = require('fs');
const path = require('path');
const pool = require('../src/db/pool');

// Parent -> child order (FK safety; waise bhi FK checks off rahenge).
const TABLES = ['AMENITY', 'AGENT', 'OWNER', 'TENANT', 'PROPERTY', 'PROPERTY_AMENITY',
  'USERS', 'INQUIRY', 'LEASE', 'TENANT_LEASE', 'PAYMENT', 'SALE',
  'CUSTOMER_ANALYSIS', 'INQUIRY_AUDIT'];

const OUT = path.join(__dirname, '..', 'db', 'seed-data.sql');
const CHUNK = 200; // ek INSERT me itni rows (file readable + fast load)

async function main() {
  const conn = await pool.getConnection();
  const lines = [];
  lines.push('-- AUTO-GENERATED by scripts/dump-seed.js — haath se edit mat karo.');
  lines.push('-- Rich Kaggle dataset (data-only). Pehle schema.sql load karo, phir ye file.');
  lines.push('USE property_mgmt;');
  lines.push('SET FOREIGN_KEY_CHECKS = 0;');
  lines.push('');

  try {
    // Pehle reverse order me truncate (idempotent — dobara load karne pe duplicate na ho).
    for (const t of [...TABLES].reverse()) lines.push(`TRUNCATE TABLE ${t};`);
    lines.push('');

    let total = 0;
    for (const table of TABLES) {
      const [rows] = await conn.query(`SELECT * FROM ${table}`);
      if (rows.length === 0) continue;
      const cols = Object.keys(rows[0]);
      const colList = cols.map((c) => `\`${c}\``).join(', ');

      lines.push(`-- ${table} (${rows.length} rows)`);
      for (let i = 0; i < rows.length; i += CHUNK) {
        const slice = rows.slice(i, i + CHUNK);
        const values = slice.map((row) => {
          const vals = cols.map((c) => conn.escape(row[c])); // mysql2 escape: null/number/date/string sab handle
          return `(${vals.join(', ')})`;
        }).join(',\n  ');
        lines.push(`INSERT INTO ${table} (${colList}) VALUES\n  ${values};`);
      }
      lines.push('');
      total += rows.length;
    }

    lines.push('SET FOREIGN_KEY_CHECKS = 1;');
    lines.push('');

    fs.writeFileSync(OUT, lines.join('\n'), 'utf8');
    const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
    console.log(`[DUMP] ✓ ${OUT}`);
    console.log(`[DUMP] ${total} rows across ${TABLES.length} tables (${kb} KB).`);
  } finally {
    conn.release();
    await pool.end();
  }
}

main().catch((err) => { console.error('[DUMP] FAIL:', err.message); process.exit(1); });
